import { useEffect, useMemo, useState, type FormEvent } from "react";
import { addInvestmentPrincipal, createPosition, deleteInvestmentPosition, fetchInvestmentFundamentals, fetchInvestmentOverview, fetchInvestmentPreferences, fetchInvestmentQuote, fetchInvestmentRates, fetchPositions, saveInvestmentPreferences, searchInvestmentTickers, type InvestmentFundamentals, type InvestmentOverview, type InvestmentPosition, type InvestmentQuote, type InvestmentRates, type InvestmentTicker } from "../api";
import { formatBrlFromCents, maskBrlInput, parseBrlToCents } from "../format";
import { ApiError, ErrorNote, PageTitle } from "./common";

type ViewMode = "cards" | "list";
const TYPES = [["all", "Todos"], ["stock", "Ações"], ["fii", "FIIs"], ["etf", "ETFs"], ["crypto", "Cripto"], ["treasury", "Tesouro"], ["cdb", "CDB"], ["fixed_income", "Renda fixa"]] as const;

export function InvestmentsPage() {
  const [overview, setOverview] = useState<InvestmentOverview | null>(null);
  const [rows, setRows] = useState<InvestmentPosition[]>([]);
  const [rates, setRates] = useState<InvestmentRates | null>(null);
  const [view, setView] = useState<ViewMode>("cards");
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [name, setName] = useState("");
  const [principal, setPrincipal] = useState("");
  const [rate, setRate] = useState("");
  const [type, setType] = useState("stock");
  const [description, setDescription] = useState("");
  const [maturity, setMaturity] = useState("");
  const [liquid, setLiquid] = useState(true);
  const [suggestions, setSuggestions] = useState<InvestmentTicker[]>([]);
  const [searching, setSearching] = useState(false);
  const [quote, setQuote] = useState<InvestmentQuote | null>(null);
  const [fundamentals, setFundamentals] = useState<InvestmentFundamentals | null>(null);
  const [marketError, setMarketError] = useState<string | null>(null);
  const [aporte, setAporte] = useState<Record<string, string>>({});
  const [positionsLoading, setPositionsLoading] = useState(true);
  const [positionsRefreshing, setPositionsRefreshing] = useState(false);

  async function load(quiet = false) {
    if (quiet) setPositionsRefreshing(true); else { setPositionsLoading(true); setError(null); }
    const positionsRequest = fetchPositions().then(setRows).catch((err) => setError(messageOf(err, "Falha ao sincronizar a carteira desta conta."))).finally(() => { setPositionsLoading(false); setPositionsRefreshing(false); });
    const supportingRequests = Promise.allSettled([
      fetchInvestmentOverview().then(setOverview),
      fetchInvestmentRates().then(setRates),
      fetchInvestmentPreferences().then((preference) => setView(preference.view_mode)),
    ]);
    await Promise.allSettled([positionsRequest, supportingRequests]);
  }
  useEffect(() => {
    void load();
    const refresh = () => { if (document.visibilityState === "visible") void load(true); };
    window.addEventListener("focus", refresh); document.addEventListener("visibilitychange", refresh);
    const timer = window.setInterval(refresh, 30_000);
    return () => { window.removeEventListener("focus", refresh); document.removeEventListener("visibilitychange", refresh); window.clearInterval(timer); };
  }, []);
  useEffect(() => {
    const query = name.trim();
    if (!showForm || query.length < 3) { setSuggestions([]); return; }
    const timer = window.setTimeout(() => { setSearching(true); void searchInvestmentTickers(query).then((items) => { const available = directTickerFallback(query, items); setSuggestions(available); const exact = available.find((item) => item.symbol.toUpperCase() === query.toUpperCase()); if (exact) { setType(exact.instrument_type || "stock"); void loadMarketDetails(exact.symbol, exact.instrument_type || "stock"); } }).catch(() => { const fallback = directTickerFallback(query, []); setSuggestions(fallback); if (fallback[0]) void loadMarketDetails(fallback[0].symbol, fallback[0].instrument_type); }).finally(() => setSearching(false)); }, 350);
    return () => window.clearTimeout(timer);
  }, [name, showForm]);

  const visible = useMemo(() => rows.filter((row) => filter === "all" || row.instrument_type === filter).filter((row) => `${row.name} ${row.description ?? ""}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))), [rows, filter, search]);
  const marketType = ["stock", "fii", "etf", "crypto"].includes(type);

  function changeName(value: string) { setName(value); setQuote(null); setFundamentals(null); setMarketError(null); const inferred = inferAssetType(value); if (inferred) setType(inferred); }
  async function loadMarketDetails(symbol: string, instrumentType: string) { setMarketError(null); const [quoteResult, fundamentalsResult] = await Promise.allSettled([fetchInvestmentQuote(symbol), instrumentType === "crypto" ? Promise.resolve(null) : fetchInvestmentFundamentals(symbol)]); if (quoteResult.status === "fulfilled" && !quoteResult.value.error) { setQuote(quoteResult.value); if (!principal && quoteResult.value.last_price > 0) setPrincipal(maskBrlInput(String(Math.round(quoteResult.value.last_price * 100)))); } else setMarketError("Não foi possível obter a cotação agora. Você ainda pode cadastrar o ativo."); if (fundamentalsResult.status === "fulfilled") setFundamentals(fundamentalsResult.value); }
  function selectTicker(item: InvestmentTicker) { setName(item.symbol); setType(item.instrument_type || "stock"); setDescription(item.name); if (item.last_price) setPrincipal(maskBrlInput(String(Math.round(item.last_price * 100)))); setSuggestions([]); void loadMarketDetails(item.symbol, item.instrument_type || "stock"); }
  function applySuggestedRate() { const value = type === "cdb" ? rates?.cdb_annual_percent : rates?.fixed_income_annual_percent; if (value != null) setRate(String(value).replace(".", ",")); }
  async function onCreate(event: FormEvent) {
    event.preventDefault(); const cents = parseBrlToCents(principal); const bps = marketType ? 0 : Math.round(Number(rate.replace(",", ".")) * 100);
    if (!name.trim() || !cents || !Number.isFinite(bps)) { setError("Preencha nome, valor e taxa válidos."); return; }
    setBusy(true); setError(null);
    try { await createPosition({ instrument_type: type, name: name.trim().toUpperCase(), description: description.trim() || null, principal_cents: cents, annual_rate_bps: bps, maturity_date: maturity || null, is_liquid: liquid }); setName(""); setPrincipal(""); setDescription(""); setMaturity(""); setShowForm(false); await load(); }
    catch (err) { setError(messageOf(err, "Não foi possível criar a posição.")); } finally { setBusy(false); }
  }
  async function changeView(next: ViewMode) { setView(next); try { await saveInvestmentPreferences(next); } catch (err) { setError(messageOf(err, "Não foi possível salvar a visualização.")); } }
  async function addPrincipal(row: InvestmentPosition) { const cents = parseBrlToCents(aporte[row.id] ?? ""); if (!cents) return; setBusy(true); try { await addInvestmentPrincipal(row.id, cents); setAporte((old) => ({ ...old, [row.id]: "" })); await load(); } catch (err) { setError(messageOf(err, "Não foi possível aportar.")); } finally { setBusy(false); } }
  async function remove(row: InvestmentPosition) { if (!window.confirm(`Excluir ${row.name}?`)) return; setBusy(true); try { await deleteInvestmentPosition(row.id); await load(); } catch (err) { setError(messageOf(err, "Não foi possível excluir.")); } finally { setBusy(false); } }

  return <div className="-mx-4 -my-5 min-h-full bg-gradient-to-br from-paper via-paper to-sky/45 px-4 py-5 sm:-mx-6 sm:px-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><PageTitle kicker="Patrimônio" title="Investimentos" /><p className="mt-2 text-sm text-muted">Acompanhe posições, encontre ativos e planeje seus próximos aportes.</p></div><button type="button" onClick={() => setShowForm((v) => !v)} className="rounded-xl bg-gold px-4 py-2.5 text-sm font-bold text-navy-deep shadow-sm">{showForm ? "Fechar cadastro" : "+ Nova posição"}</button></div>
    <div className="mt-4"><ErrorNote message={error} /></div>
    {overview ? <section className="mt-4 grid gap-3 sm:grid-cols-3">{[["Total alocado", overview.total_allocated_cents, "navy"], ["Rendimento estimado", overview.total_yield_cents, "teal"], ["Estimado por mês", overview.estimated_monthly_yield_cents, "gold"]].map(([label, value, tone]) => <Metric key={String(label)} label={String(label)} value={Number(value)} tone={String(tone)} />)}</section> : null}
    {showForm ? <form onSubmit={onCreate} className="wp-rise mt-4 overflow-visible rounded-3xl border border-navy/8 bg-white/90 shadow-[0_18px_55px_rgba(20,28,42,0.08)]"><header className="border-b border-navy/8 bg-cream/30 px-5 py-3"><h2 className="font-serif text-xl text-navy-deep">Adicionar investimento</h2><p className="text-xs text-muted">Pesquise pelo nome ou ticker; o tipo e os dados disponíveis serão preenchidos automaticamente.</p></header><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4">
      <label className="relative"><FieldLabel>Ativo ou título</FieldLabel><input required value={name} onChange={(e) => changeName(e.target.value)} placeholder="Ex.: FIQE3, bitcoin ou CDB" autoComplete="off" className="field" />{searching ? <span className="absolute right-3 top-9 text-xs text-muted">Buscando…</span> : null}{suggestions.length ? <ul className="absolute z-30 mt-1 max-h-64 w-full overflow-auto rounded-xl border border-navy/10 bg-white p-1 shadow-xl">{suggestions.map((item) => <li key={`${item.instrument_type}-${item.symbol}`}><button type="button" onClick={() => selectTicker(item)} className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left hover:bg-sage/50"><span><b className="text-sm text-navy">{item.symbol}</b><small className="block truncate text-muted">{item.name} · {typeLabel(item.instrument_type)}</small></span>{item.last_price != null ? <span className="text-xs font-bold text-teal-deep">{(item.currency || "BRL") === "BRL" ? "R$ " : `${item.currency || "USD"} `}{item.last_price.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</span> : null}</button></li>)}</ul> : null}</label>
      <label><FieldLabel>Tipo</FieldLabel><select value={type} onChange={(e) => setType(e.target.value)} className="field">{TYPES.slice(1).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <label><FieldLabel>Valor aplicado</FieldLabel><input required inputMode="numeric" value={principal} onChange={(e) => setPrincipal(maskBrlInput(e.target.value))} placeholder="R$ 0,00" className="field" /></label>
      {!marketType ? <label><FieldLabel>Rentabilidade anual</FieldLabel><div className="flex gap-1"><input required inputMode="decimal" value={rate} onChange={(e) => setRate(e.target.value)} placeholder="% a.a." className="field min-w-0" /><button type="button" onClick={applySuggestedRate} className="rounded-lg bg-sage px-2 text-[10px] font-bold text-teal-deep">Usar mercado</button></div></label> : <label><FieldLabel>Descrição</FieldLabel><input value={description} onChange={(e) => setDescription(e.target.value)} className="field" /></label>}
      <label><FieldLabel>Vencimento</FieldLabel><input type="date" value={maturity} onChange={(e) => setMaturity(e.target.value)} className="field" /></label><label className="flex items-end"><span className="flex h-10 w-full items-center gap-2 rounded-lg bg-cream/50 px-3 text-sm"><input type="checkbox" checked={liquid} onChange={(e) => setLiquid(e.target.checked)} className="accent-teal" /> Liquidez disponível</span></label><button disabled={busy} className="h-10 self-end rounded-lg bg-teal px-5 text-sm font-bold text-white disabled:opacity-50">{busy ? "Salvando…" : "Adicionar posição"}</button>
    </div>{quote || fundamentals || marketError ? <MarketSnapshot quote={quote} fundamentals={fundamentals} error={marketError} /> : null}{fundamentals ? <ExtraFundamentals data={fundamentals} /> : null}</form> : null}
    <section className="mt-4 overflow-hidden rounded-[1.6rem] border border-navy/8 bg-white/90 shadow-[0_18px_55px_rgba(20,28,42,0.08)]"><header className="border-b border-navy/8 bg-gradient-to-r from-white via-white to-sage/40 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-xl text-navy-deep">Sua carteira</h2><p className="text-xs text-muted">{positionsLoading ? "Sincronizando sua conta…" : `${visible.length} de ${rows.length} posições`}{positionsRefreshing ? " · atualizando" : ""}</p></div><div className="flex rounded-xl border border-navy/10 bg-white p-1"><ViewButton active={view === "cards"} onClick={() => void changeView("cards")}>▦ Cards</ViewButton><ViewButton active={view === "list"} onClick={() => void changeView("list")}>☷ Lista</ViewButton></div></div><div className="mt-4 grid gap-2 md:grid-cols-[1fr_220px]"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar na carteira…" className="field bg-cream/25" /><select value={filter} onChange={(e) => setFilter(e.target.value)} className="field bg-cream/25">{TYPES.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></header>
      {positionsLoading ? <PortfolioSkeleton view={view} /> : !visible.length ? <div className="p-14 text-center text-sm text-muted">Nenhuma posição encontrada nesta conta.</div> : view === "cards" ? <div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3 sm:p-5">{visible.map((row) => <PositionCard key={row.id} row={row} aporte={aporte[row.id] ?? ""} busy={busy} onAporte={(value) => setAporte((old) => ({ ...old, [row.id]: maskBrlInput(value) }))} onAdd={() => void addPrincipal(row)} onDelete={() => void remove(row)} />)}</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-cream/60 text-[10px] uppercase tracking-wider text-muted"><tr><th className="px-5 py-3">Ativo</th><th className="px-3 py-3">Tipo</th><th className="px-3 py-3">Condições</th><th className="px-3 py-3 text-right">Aplicado</th><th className="px-5 py-3 text-right">Ações</th></tr></thead><tbody className="divide-y divide-navy/8">{visible.map((row) => <tr key={row.id} className="hover:bg-sage/20"><td className="px-5 py-3"><b>{row.name}</b><small className="block text-muted">{row.description}</small></td><td className="px-3 py-3">{typeLabel(row.instrument_type)}</td><td className="px-3 py-3 text-xs text-muted">{row.annual_rate_bps ? `${(row.annual_rate_bps / 100).toFixed(2)}% a.a.` : "Cotação de mercado"} · {row.is_liquid ? "líquido" : "vencimento"}</td><td className="px-3 py-3 text-right font-bold">{formatBrlFromCents(row.principal_cents)}</td><td className="px-5 py-3 text-right"><button type="button" onClick={() => void remove(row)} className="text-xs font-semibold text-red-700">Excluir</button></td></tr>)}</tbody></table></div>}
    </section>
  </div>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`rounded-2xl border border-navy/8 border-l-4 ${tone === "teal" ? "border-l-teal" : tone === "gold" ? "border-l-gold" : "border-l-navy"} bg-white/90 px-4 py-3.5 shadow-sm`}><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-muted">{label}</p><p className="mt-1 font-display text-2xl font-semibold text-navy-deep">{formatBrlFromCents(value)}</p></article>; }
function PositionCard({ row, aporte, busy, onAporte, onAdd, onDelete }: { row: InvestmentPosition; aporte: string; busy: boolean; onAporte: (v: string) => void; onAdd: () => void; onDelete: () => void }) { const market = ["stock", "fii", "etf", "crypto"].includes(row.instrument_type); return <article className={`group overflow-hidden rounded-3xl border border-navy/8 shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${market ? "bg-gradient-to-br from-navy-deep to-navy text-white" : "bg-gradient-to-br from-white to-sage/40 text-navy"}`}><div className="p-5"><div className="flex justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${market ? "bg-white/12 text-gold" : "bg-teal/10 text-teal-deep"}`}>{typeLabel(row.instrument_type)}</span><button type="button" onClick={onDelete} className="text-xs opacity-60 hover:text-red-500 hover:opacity-100">Excluir</button></div><h3 className="mt-5 font-display text-2xl font-semibold">{row.name}</h3><p className={`mt-1 line-clamp-1 text-xs ${market ? "text-white/60" : "text-muted"}`}>{row.description || (market ? "Ativo de mercado" : "Renda fixa")}</p><p className="mt-5 text-3xl font-bold tabular-nums">{formatBrlFromCents(row.principal_cents)}</p><div className={`mt-4 grid grid-cols-2 gap-2 rounded-2xl p-3 text-xs ${market ? "bg-white/8" : "bg-white/70"}`}><span><small className="block opacity-60">Rentabilidade</small><b>{row.annual_rate_bps ? `${(row.annual_rate_bps / 100).toFixed(2)}% a.a.` : "Mercado"}</b></span><span><small className="block opacity-60">Liquidez</small><b>{row.is_liquid ? "Disponível" : row.maturity_date || "No vencimento"}</b></span></div></div><div className={`flex gap-2 border-t p-3 ${market ? "border-white/10" : "border-navy/8"}`}><input inputMode="numeric" value={aporte} onChange={(e) => onAporte(e.target.value)} placeholder="Novo aporte" className={`min-w-0 flex-1 rounded-xl px-3 py-2 text-sm ${market ? "bg-white/10 text-white placeholder:text-white/40" : "border border-navy/10 bg-white"}`} /><button type="button" disabled={busy || !aporte} onClick={onAdd} className="rounded-xl bg-gold px-3 text-xs font-bold text-navy-deep disabled:opacity-40">Aportar</button></div></article>; }
function ViewButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: string }) { return <button type="button" onClick={onClick} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${active ? "bg-navy-deep text-white" : "text-muted"}`}>{children}</button>; }
function PortfolioSkeleton({ view }: { view: ViewMode }) { return view === "cards" ? <div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3 sm:p-5">{[0, 1, 2].map((item) => <div key={item} className="h-64 animate-pulse rounded-3xl bg-navy/10" />)}</div> : <div className="space-y-2 p-5">{[0, 1, 2, 3].map((item) => <div key={item} className="h-14 animate-pulse rounded-xl bg-navy/10" />)}</div>; }
function FieldLabel({ children }: { children: string }) { return <span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-muted">{children}</span>; }
function typeLabel(type: string) { return TYPES.find(([key]) => key === type)?.[1] ?? type.replaceAll("_", " "); }
export function inferAssetType(raw: string): string | null { const value = raw.trim().toLocaleLowerCase("pt-BR"); if (/\b(bitcoin|btc|ethereum|ether|eth|solana|sol|bnb|xrp|cardano|ada|dogecoin|doge|litecoin|ltc|usdt|usdc|cripto|crypto)\b/.test(value)) return "crypto"; if (/^[a-z]{4}\d{1,2}$/i.test(value)) return "stock"; if (/\b(cdb|renda fixa|lci|lca|deb[eê]nture)\b/.test(value)) return "cdb"; if (/\b(tesouro|selic|ipca\+)\b/.test(value)) return "treasury"; return null; }
export function directTickerFallback(raw: string, items: InvestmentTicker[]): InvestmentTicker[] { const symbol = raw.trim().toUpperCase(); if (items.length || !/^[A-Z]{4}\d{1,2}$/.test(symbol)) return items; return [{ symbol, name: `${symbol} · ativo B3`, instrument_type: symbol.endsWith("11") ? "fii" : "stock" }]; }
function MarketSnapshot({ quote, fundamentals, error }: { quote: InvestmentQuote | null; fundamentals: InvestmentFundamentals | null; error: string | null }) { const metrics = fundamentals ? [["P/L", fundamentals.pl], ["P/VP", fundamentals.pvp], ["ROE", fundamentals.roe], ["Dividend yield", fundamentals.dividend_yield_12m || fundamentals.dividend_yield], ["EV/EBITDA", fundamentals.ev_ebitda], ["Margem líquida", fundamentals.net_margin], ["Dív. líquida/EBITDA", fundamentals.net_debt_ebitda], ["LPA", fundamentals.eps]].filter(([, value]) => value) as string[][] : []; return <section className="mx-4 mb-4 rounded-2xl bg-gradient-to-br from-navy-deep to-navy p-4 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-gold">Dados essenciais do ativo</p><h3 className="mt-1 font-display text-xl">{fundamentals?.company_name || quote?.symbol || "Cotação indisponível"}</h3><p className="text-xs text-white/55">Fonte: {quote?.source || fundamentals?.source || "mercado"}</p></div>{quote ? <div className="text-right"><p className="font-display text-2xl font-semibold">{formatMarketValue(quote.last_price, quote.currency)}</p><p className={`text-xs font-bold ${(quote.change_24h_percent || 0) >= 0 ? "text-emerald-300" : "text-red-300"}`}>{quote.change_24h_percent == null ? "Variação indisponível" : `${quote.change_24h_percent >= 0 ? "+" : ""}${quote.change_24h_percent.toLocaleString("pt-BR", { maximumFractionDigits: 2 })}%`}</p></div> : null}</div>{quote ? <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><MarketDatum label="Máxima" value={quote.day_high == null ? null : formatMarketValue(quote.day_high, quote.currency)} /><MarketDatum label="Mínima" value={quote.day_low == null ? null : formatMarketValue(quote.day_low, quote.currency)} /><MarketDatum label="Volume" value={quote.volume_24h == null ? null : quote.volume_24h.toLocaleString("pt-BR", { notation: "compact" })} /><MarketDatum label="Atualização" value={quote.as_of ? new Date(quote.as_of).toLocaleDateString("pt-BR") : null} /></div> : null}{metrics.length ? <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{metrics.map(([label, value]) => <MarketDatum key={label} label={label} value={value} />)}</div> : null}{error ? <p className="mt-3 rounded-xl bg-amber-400/15 px-3 py-2 text-xs text-amber-100">{error}</p> : null}</section>; }
function MarketDatum({ label, value }: { label: string; value?: string | null }) { return <div className="rounded-xl bg-white/8 px-3 py-2"><small className="block text-[10px] uppercase text-white/50">{label}</small><b className="text-sm">{value || "—"}</b></div>; }
function ExtraFundamentals({ data }: { data: InvestmentFundamentals }) { const rows = [["ROIC", data.roic], ["Margem EBIT", data.ebit_margin], ["Payout", data.payout_ratio], ["Liquidez corrente", data.current_ratio], ["Dívida/Patrimônio", data.debt_to_equity], ["Crescimento da receita", data.revenue_growth], ["Liquidez diária", data.daily_liquidity], ["Beta", data.beta], ["Máxima em 52 semanas", data.week_52_high], ["Mínima em 52 semanas", data.week_52_low], ["Vacância financeira", data.vacancy_financial], ["Prazo médio dos contratos", data.contract_term_wault], ["Contratos atípicos", data.atypical_contracts_ratio], ["Concentração top 5", data.top5_tenants_concentration]].filter(([, value]) => value) as string[][]; if (!rows.length) return null; return <section className="mx-4 mb-4 rounded-2xl border border-navy/8 bg-cream/45 p-4"><div className="mb-3"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-teal-deep">Análise complementar</p><p className="text-xs text-muted">Indicadores adicionais disponíveis para este tipo de ativo.</p></div><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{rows.map(([label, value]) => <div key={label} className="rounded-xl border border-navy/8 bg-white px-3 py-2"><small className="block text-[10px] uppercase text-muted">{label}</small><b className="text-sm text-navy-deep">{value}</b></div>)}</div></section>; }
function formatMarketValue(value: number, currency = "BRL") { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: currency || "BRL" }).format(value); }
function messageOf(error: unknown, fallback: string) { return error instanceof ApiError ? error.message : error instanceof Error ? error.message : fallback; }
